from typing import Optional, Tuple

class ElGamalBase:
    def __init__(self, bits: int, predefined_group: bool = False) -> None: ...
    
    def generate_keys(self) -> None: ...
    
    def set_keys(self, public: int, private: int) -> None: ...
    
    def generate_params(self, group_params: Optional[Tuple[int, int]] = None) -> None: ...
    
    @property
    def priv_key(self) -> Optional[int]: ...

    @property
    def pub_key(self) -> Optional[int]: ...